In [6]:
import sys
from pathlib import Path
PROJECT_ROOT = Path.cwd().parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

In [7]:
from app.catalog.loader import load_catalog
import pandas as pd

In [8]:
catalog = load_catalog()
df = pd.DataFrame(catalog)

In [9]:
from app.catalog.preprocess import (
    build_search_document,
    extract_duration_minutes,
    is_report,
)

In [10]:
df["search_document"] = [
    build_search_document(a)
    for a in catalog
]
df["duration_minutes"] = df["duration"].apply(extract_duration_minutes)
df["is_report"] = df["name"].apply(is_report)

In [11]:
df[
    [
        "name",
        "duration",
        "duration_minutes",
        "is_report"
    ]
].head(15)

,name,duration,duration_minutes,is_report
0,Global Skills Development Report,,NaN,True
1,.NET Framework 4.5,30 minutes,30.0,False
2,.NET MVC (New),17 minutes,17.0,False
3,.NET MVVM (New),5 minutes,5.0,False
4,.NET WCF (New),11 minutes,11.0,False
5,.NET WPF (New),9 minutes,9.0,False
6,.NET XAML (New),5 minutes,5.0,False
7,Accounts Payable (New),9 minutes,9.0,False
8,Accounts Payable Simulation (New),8 minutes,8.0,False
9,Accounts Receivable (New),13 minutes,13.0,False
10,Accounts Receivable Simulation (New),8 minutes,8.0,False
11,ADO.NET (New),10 minutes,10.0,False
12,Adobe Experience Manager (New),17 minutes,17.0,False
13,Adobe Photoshop CC,20 minutes,20.0,False
14,Aeronautical Engineering (New),10 minutes,10.0,False

In [12]:
df["assessment_type"] = df["keys"].apply(
    lambda x: ", ".join(x)
)

df["job_level"] = df["job_levels"].apply(
    lambda x: ", ".join(x)
)

df["language"] = df["languages"].apply(
    lambda x: ", ".join(x)
)

In [13]:
df[
    [
        "name",
        "assessment_type",
        "job_level",
        "language"
    ]
].head()

,name,assessment_type,job_level,language
0,Global Skills Development Report,"Ability & Aptitude, Assessment Exercises, Biod...","Director, Entry-Level, Executive, General Popu...",
1,.NET Framework 4.5,Knowledge & Skills,"Professional Individual Contributor, Mid-Profe...",English (USA)
2,.NET MVC (New),Knowledge & Skills,"Mid-Professional, Professional Individual Cont...",English (USA)
3,.NET MVVM (New),Knowledge & Skills,"Mid-Professional, Professional Individual Cont...",English (USA)
4,.NET WCF (New),Knowledge & Skills,"Mid-Professional, Professional Individual Cont...",English (USA)

In [14]:
from pathlib import Path
output = Path("../data/processed/catalog_processed.csv")
df.to_csv(output, index=False)

In [15]:
df.columns.tolist()

['entity_id',
 'name',
 'link',
 'scraped_at',
 'job_levels',
 'job_levels_raw',
 'languages',
 'languages_raw',
 'duration',
 'duration_raw',
 'status',
 'remote',
 'adaptive',
 'description',
 'keys',
 'search_document',
 'duration_minutes',
 'is_report',
 'assessment_type',
 'job_level',
 'language']